server.port=8081
spring.application.name=player-service

spring.datasource.url=jdbc:postgresql://localhost:5432/blueroute
spring.datasource.username=postgres
spring.datasource.password=postgres

session.service.url=${SESSION_SERVICE_URL:http://localhost:8084}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false