services:
  postgres:
    image: postgres:16
    container_name: blueroute-postgres
    environment:
      POSTGRES_DB: blueroute
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/blue-route
    container_name: blueroute-backend
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/blueroute
      DB_USER: postgres
      DB_PASSWORD: postgres
      PLAYER_SERVICE_URL: http://player-service:8081
    ports:
      - "8080:8080"

  player-service:
    build: ./player-service
    container_name: blueroute-player-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blueroute
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"

  ship-service:
    build: ./ship-service
    container_name: blueroute-ship-service
    depends_on:
      - postgres
      - player-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blueroute
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      PLAYER_SERVICE_URL: http://player-service:8081
    ports:
      - "8082:8082"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://10.0.40.187:8080
    container_name: blueroute-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:

