spring.datasource.url=jdbc:postgresql://blueroute-postgres:5432/blueroute
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

game.tick.rate=5000
session.heartbeat.timeout-seconds=20