spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

player.service.url=http://player-service:8081
ship.service.url=http://ship-service:8082

game.tick.rate=5000
session.heartbeat.timeout-seconds=20