spring.datasource.url=jdbc:postgresql://DEV_HOST:5432/blueroute
spring.datasource.username=DEV_USER
spring.datasource.password=DEV_PASSWORD

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

game.tick.rate=5000