server.port=8085
spring.application.name=event-service

travel.service.url=${TRAVEL_SERVICE_URL:http://localhost:8083}
ship.service.url=${SHIP_SERVICE_URL:http://localhost:8082}
player.service.url=${PLAYER_SERVICE_URL:http://localhost:8081}
session.service.url=${SESSION_SERVICE_URL:http://localhost:8084}
backend.url=${BACKEND_URL:http://localhost:8080}